### ISSUE TITLE
검색 페이지 CSS 작성

### ISSUE THREAD

**Issue by 1Tsw0rd** [Challenge02/Challenge02-FE#5]
# Description
검색 결과 출력 페이지

## Todo
- [ ] 로고 css
- [ ] 검색 입력 css
- [x] 아티스트 검색결과 css
- [x] 곡 검색결과 css
- [x] 가사 검색결과 css
- [x] 더보기 css

## Etc
기타사항을 작성해주세요.
